### ISSUE TITLE
Editor: keyboard shortcuts

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#147]
There are couple of issues open regarding keyboard shortcuts.
- ~~`Ctrl + L`: https://github.com/ethereum/browser-solidity/issues/76 (@raineorshine)~~_done_
- ~~`Ctrl + T`: https://github.com/chriseth/browser-solidity/issues/112 (@ethernomad)~~ _done_
- ~~`Ctrl + F`: https://github.com/chriseth/browser-solidity/issues/160 (@patcon)~~ _done_
- `Ctrl + D`: https://github.com/chriseth/browser-solidity/issues/165 (@VoR0220)

It would be nice to discuss which ones should be considered.  Any other additions?

A possible way to support them in ACE is explained here: https://github.com/ajaxorg/ace/issues/36#issuecomment-6941120

**Comment by Denton-L** [comment]
Just personal opinion, but I think Ctrl+L, Ctrl+T and Ctrl+F shouldn't be clobbered as those are frequently used. Ctrl+D isn't that commonly used (favouriting a page), though, so that should stay as is.

**Comment by VoR0220** [comment]
Ctrl+D I meant in the sense of how Sublime uses it whereby you can copy multiple lines of the same highlighted value and then edit them simultaneously...I think in some form, this should be implemented. It's a joy to use.

**Comment by Denton-L** [comment]
I think this is a slippery slope, though. If we're including Sublime shortcuts, why not include emacs shortcuts? Then why not include a vim-mode?

Actually, come to think of it, I think ACE supports emacs and vim by default. Would it be possible to include user support?

**Comment by axic** [comment]
Added ctrl-f and ctrl-t to #148. Can you test? On Mac it seems to work.

**Comment by axic** [comment]
Ctrl + F/Ctrl + T were fixed. What should happen to Ctrl + D and Ctrl + L?

**Comment by chriseth** [comment]
ctrl+l is a tough one. I personally use it a lot to go to the address bar, but I can see that some people could use it to jump to specific lines.

**Comment by orgy** [comment]
what about just setting an option somewhere for the user to decide whether or not (s)he wants to clobber individual shortcuts?

**Comment by chriseth** [comment]
We can do that, where the default would be not to hijack regular browser shortcuts.

**Comment by hiqua** [comment]
CTRL-F is still buggy for me, as I wrote in https://github.com/ethereum/browser-solidity/issues/894#issuecomment-344229077.

**Comment by ahmednofal** [comment]
if you can please add a vim mode to the editor that would be awesome. Thank you for the effort and beautiful work.

**Comment by yann300** [comment]
added https://github.com/ethereum/remix-ide/issues/2069
